### ISSUE TITLE
The $memberOf operator want expected to be supported.

### ISSUE THREAD

**Issue by vampireslove** [thiagolvlsantos/json-predicate#2]
public void testMemberOfMatch() throws Exception {
        String rule ="{\n" +
                "  \"$and\": [\n" +
                "    {\n" +
                "      \"str\": {\n" +
                "        \"$memberOf\": [\n" +
                "          \"ab\",\n" +
                "          \"bc\",\n" +
                "          \"ef\"\n" +
                "        ]\n" +
                "      }\n" +
                "    }\n" +
                "  ]\n" +
                "}";
        Predicate<Object> pred = factory.read(rule.getBytes());
        Map<String,Object> map = new HashMap<>(2);
        map.put("str","ab");
        boolean test = pred.test(map);
        Assert.assertTrue(test);
    }

**Comment by thiagolvlsantos** [comment]
@vampireslove,

Operator (it`s negative form) and tests added to the codebase and readme.

Thanks for the suggestion, it will open doors for other set operators.

Closing this one. :)
